### ISSUE TITLE
FC on initial p/w setup

### ISSUE THREAD

**Issue by djhalliday** [guardianproject/notecipher#1]
Tested the app this evening on a large variety of lab devices and got FC on every one except the trusty n1. The logcat info for the first device failure can be found here: http://pastebin.com/FS1zM8xw. I didn't logcat on any additional devices as the bug looks to be the same (at least on the surface). 

ID-----Device_Type------------(ROM)
01-----mytouch 3g--------------(stock 2.2.1) 
02-----htc magic-----------------(cm 6.1)
03-----moto droid---------------(stock 2.2.1)
04-----moto droid---------------(stock 2.2.2)
05-----htc_wildfire--------------(stock 2.2.1)

**Comment by n8fr8** [comment]
well it could be b/c i linked it to libraries pulled from an N1, rather than files from the NDK. Hmm. Will have to confer with _hc.

D/dalvikvm(  420): Trying to load lib /data/data/info.guardianproject.notepadbot/lib/libsqlcipher_android.so 0x4353a018
I/dalvikvm(  420): Unable to dlopen(/data/data/info.guardianproject.notepadbot/lib/libsqlcipher_android.so): Cannot load library: link_image[1995]: failed to link libsqlcipher_android.so
I/dalvikvm(  420):

**Comment by n8fr8** [comment]
okay, i found the SDK build of the library in my Android OS build here:

/home/n8fr8/android/mydroid/out/target/product/generic/obj/SHARED_LIBRARIES/libutils_intermediates/LINKED

going to try linking against that

**Comment by abeluck** [comment]
Closing stale report.
