### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by alterechtschreibung** [guardianproject/notecipher#8]
We want to add SQLCipher for Android to the FOSS-Market F-Droid. Unfortunately, we can't build it, see: http://f-droid.org/forums/topic/notecipher-the-guardian-project/#post-4268

Please get in touch with us to come to a solution.

**Comment by dalb8** [comment]
Well, we could build it but, the fact that the native code is in another repo presents some technical difficulties. Due to  limited resources it may take a while before we get around to building this one.

**Comment by abeluck** [comment]
NoteCipher was more of a proof of concept SQLCipher using app. It could really use some love on the UI end to make it an even remotely enjoyable notetaking app.

As for the native code being in another repo, we could make it a git submodule, would that help? We've been doing that with our more recent projects with much success.

**Comment by dalb8** [comment]
Yes I hesitated to include it because it is , as you say, a bit undercooked. But if you don't mind doing the submodule thing , great. alterechtschreibung argues that we don't have any other encrypted  note app which is a fair point. We have http://f-droid.org/forums/topic/mininoteviewer/ in the queue , but we would need to get that into a repo. I would suggest Keepassdroid right now if anybody asked, I suppose, though I use Cryptonite myself

**Comment by n8fr8** [comment]
Notepadbot aka NoteCipher has also evolved into a more general purpose text and media store called SyncSafe that we hope to update in the near future. 

As a side note, NoteCipher's build of SQLCipher also need to be updated to v2, so it can run on Android 3/4.

**Comment by abeluck** [comment]
Closing stale bug reports.
